# Generated by Django 4.2.1 on 2023-06-03 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='PhoneNumber',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='client',
            name='name',
            field=models.CharField(default='opal', max_length=30),
        ),
    ]
