# Generated by Django 4.2.1 on 2023-06-03 08:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_alter_client_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='PhoneNumber',
            field=models.CharField(default='', max_length=10),
        ),
    ]
