# Generated by Django 4.2.1 on 2023-06-08 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_alter_client_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('user', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('numOfTry', models.IntegerField(default=0)),
            ],
        ),
    ]
